### ISSUE TITLE
Save anova_neat in .doc file?

### ISSUE THREAD

**Issue by teindor** [gasparl/neatstats#1]
I used the following code: anova_neat(hr, values = c("first_Cong","first_InCong","second_Cong","second_InCong"), 
           within_ids = list(
             time = c('first', 'second'),
             cong = c('_In', '_Cong')),
           between_vars = 'group', bf_added = T)

It works nicely. Could that be saved directly into a printable table such as into a .doc (Word) file?

**Comment by gasparl** [comment]
Woops, sorry, I didn't notice this earlier. Anyway, no, sorry but there is no such option at the moment and I don't really plan on implementing it, since I don't normally need to put ANOVAs into tables, and even if I did, it seems rather easy to just divide the text into columns. You could do e.g. "multi-editing" (multiple cursors / multiple selected lines simultaneously) in Atom or similar text editors, jumping between words using Ctrl+ArrowKey, to divide all lines into columns at the same time (and remove unnecessary commas etc.).
But I'm glad the function works nicely otherwise.
